/*
This query will return the ten most searched destinations for each 10 minute interval since 00:00:00.
*/

WITH 
  T1 AS
    (SELECT TIME, DESTINATION, (FLOOR ( ( EXTRACT(HOUR FROM TIME) * 60 + EXTRACT(MINUTE FROM TIME) ) / 10) * 10) || '-' || ((FLOOR ( ( EXTRACT(HOUR FROM TIME) * 60 + EXTRACT(MINUTE FROM TIME) ) / 10) * 10) + 9) AS MIN_INTERVAL
    FROM BIWETL.JUNK_CLICKLOG
    WHERE ACTION = 'Search'),
  T2 AS
    (SELECT MIN_INTERVAL, DESTINATION, COUNT(DESTINATION) DEST_COUNT
    FROM T1
    GROUP BY MIN_INTERVAL, DESTINATION),
  T3 AS
    (SELECT MIN_INTERVAL, DESTINATION, ROW_NUMBER() OVER (PARTITION BY MIN_INTERVAL ORDER BY MIN_INTERVAL ASC, DEST_COUNT DESC) AS TOP_DEST_ORDER
    FROM T2)
SELECT MIN_INTERVAL, DESTINATION 
FROM T3 
WHERE TOP_DEST_ORDER <= 10 
ORDER BY MIN_INTERVAL, TOP_DEST_ORDER;